#include <stdio.h>
#include "levels.h"

/* Helper macros to build canonical solution instructions */
#define SOL_DEL(pos)  { OP_DELETE, (pos), 0, '\0' }
#define SOL_INS(pos, b) { OP_INSERT, (pos), 0, (b) }
#define SOL_REV(pos, len) { OP_REVERSE, (pos), (len), '\0' }
#define SOL_SWP(p1, p2)  { OP_SWAP, (p1), (p2), '\0' }

static const LevelDefinition LEVELS[] = {
    {
        1,
        "First Repair",
        "Teach INSERT",
        "DNA tape, transcription, codons, and the RUN command",
        3, 4,        // target codon count (including STOP)
        8, 14,       // tape length range
        0, 1, 0, 0,  // inventory: DEL x0, INS x1, REV x0, SWAP x0
        1,           // difficulty
        1,           // intended_depth
        CORRUPTION_DEL_ONLY,
        "The tape is missing a base that should be there.",
        "Compare the target output to what the tape produces. One codon is wrong.",
        "The tape is one base too short. You need to INSERT a base.",
        "Press RUN to execute the tape and see the result.",
        /* Level data */
        "TACCCCTTAATC",         // target DNA
        "TACCCCTTAAC",          // initial DNA
        { SOL_INS(11, 'T') },   // solution
        1,                      // solution count
    },
    {
        2,
        "Position Matters",
        "Teach that insertion position matters",
        "Positions matter: where you insert changes the outcome",
        4, 4,
        8, 11,
        0, 1, 0, 0,
        2,
        1,
        CORRUPTION_DEL_ONLY,
        "There are multiple places you could insert a base.",
        "Try each position and see which one produces the right codons.",
        "Check the reading frame after each insertion.",
        "The correct insertion restores the proper codon grouping.",
        "TACACCTACATT",
        "TACACCTACAT",
        { SOL_INS(11, 'T') },
        1,
    },
    {
        3,
        "Cut the Error",
        "Introduce DELETE",
        "Deleting one base can fix the entire downstream sequence",
        3, 4,
        10, 14,
        1, 0, 0, 0,
        3,
        1,
        CORRUPTION_INS_ONLY,
        "There's an extra base that shouldn't be there.",
        "The extra base shifts the reading frame for all codons after it.",
        "Find and delete the base that's causing the frame shift.",
        "After deletion, the remaining bases should group correctly.",
        "TACCCCACT",
        "TACCCGCACT",
        { SOL_DEL(6) },
        1,
    },
    {
        4,
        "Find the Break",
        "Make frame disruption more obvious",
        "FRAME ERROR tells you the reading frame is broken",
        4, 5,
        10, 15,
        1, 0, 0, 0,
        4,
        1,
        CORRUPTION_INS_ONLY,
        "The tape is one base too long.",
        "A FRAME ERROR means the length isn't divisible by 3.",
        "Try deleting each candidate base and running the machine.",
        "The correct deletion restores the proper codon grouping.",
        "TACAACTTAATC",
        "TACAGACTTAATC",
        { SOL_DEL(5) },
        1,
    },
    {
        5,
        "Wrong Letter",
        "Introduce candidate selection",
        "First mismatch does not automatically reveal the correct edit position",
        4, 5,
        10, 16,
        1, 1, 0, 0,
        5,
        2,
        CORRUPTION_RANDOM,
        "Multiple edits could fix the frame.",
        "Try each position and run the machine to see the full result.",
        "Only the correct combination makes ALL codons match the target.",
        "Don't assume - verify with RUN.",
        "TACACACAGACT",
        "TAAGCACAGACT",
        { SOL_DEL(4), SOL_INS(3, 'C') },
        2,
    },
    {
        6,
        "Premature STOP",
        "Teach STOP codons",
        "Check the ENTIRE execution, not just the first codon",
        5, 5,
        12, 17,
        1, 0, 0, 0,
        6,
        1,
        CORRUPTION_INS_ONLY,
        "An edit might look right for the first codon but fail later.",
        "Run the full execution to check ALL codons, not just the first.",
        "A premature STOP codon terminates translation too early.",
        "Make sure no non-terminal codon produces STOP.",
        "TACCCCTTAAAAATC",
        "TACCCCTGTAAAAATC",
        { SOL_DEL(8) },
        1,
    },
    {
        7,
        "Repair Protocol",
        "Combine INSERT and DELETE",
        "Diagnostic reasoning: determine the problem before choosing the fix",
        4, 5,
        10, 16,
        1, 1, 0, 0,
        7,
        2,
        CORRUPTION_INS_DEL,
        "More than one operation type seems available.",
        "Check the tape length: is it a multiple of 3?",
        "If too long â†’ DELETE. If too short â†’ INSERT.",
        "Verify all codons match after your edit.",
        "TACACACAGACT",
        "TGAACACAGACT",
        { SOL_DEL(2), SOL_INS(3, 'C') },
        2,
    },
    {
        8,
        "Reverse Engineering",
        "Introduce REVERSE",
        "Reversing changes the order of bases within a segment without changing length",
        4, 4,
        9, 15,
        0, 0, 1, 0,
        8,
        1,
        CORRUPTION_REV_ONLY,
        "REVERSE changes the order of bases in a segment.",
        "It's a string reversal, not a reverse-complement.",
        "Find the segment that needs to be reversed to match the target.",
        "After reversal, check that all codons translate correctly.",
        "TACCCCACAACT",
        "TCAACACCCCAT",
        { SOL_REV(1, 12) },
        1,
    },
    {
        9,
        "Swap Test",
        "Introduce SWAP",
        "Swapping exchanges two bases without changing length",
        4, 5,
        9, 15,
        0, 0, 0, 1,
        9,
        1,
        CORRUPTION_SWP_ONLY,
        "SWAP exchanges the bases at two positions.",
        "Find the two positions where bases need to be swapped.",
        "The swap doesn't change sequence length, only base order.",
        "After swapping, verify all codons match the target.",
        "TACACAAAAACT",
        "TACCAAAAAACT",
        { SOL_SWP(4, 5) },
        1,
    },
    {
        10,
        "Two-Step Repair",
        "Combine DELETE and INSERT",
        "Instruction order matters because positions refer to current tape state",
        5, 5,
        12, 17,
        1, 1, 0, 0,
        10,
        2,
        CORRUPTION_RANDOM,
        "One instruction is not enough to reach the target.",
        "Think about what combination of operations is needed.",
        "The order of operations matters - try different sequences.",
        "After each instruction, the tape changes, so positions shift.",
        "TACCTCTATTCCACT",
        "TACCTCTTATCCACT",
        { SOL_DEL(8), SOL_INS(9, 'T') },
        2,
    },
    {
        11,
        "Limited Toolkit",
        "Full toolkit, plan under constraints",
        "You must choose which instructions to use and in what order",
        5, 6,
        12, 18,
        1, 1, 1, 1,
        11,
        2,
        CORRUPTION_RANDOM,
        "You have a limited number of each instruction type.",
        "Plan which instructions to use before executing.",
        "Running out of a key instruction means you can't complete the puzzle.",
        "Think about the minimum number of operations needed.",
        "TACGGGCATCGCACT",
        "CGGGGCATATCGCACT",
        { SOL_DEL(2), SOL_REV(1, 7) },
        2,
    },
    {
        12,
        "Frame Recovery",
        "Combine DELETE and REVERSE",
        "Operation ordering becomes part of the puzzle",
        5, 6,
        16, 19,
        1, 0, 1, 0,
        12,
        2,
        CORRUPTION_DEL_REV,
        "The first codon might look correct, but check downstream.",
        "A frameshift at one position affects every codon after it.",
        "DEL then REV may behave differently from REV then DEL.",
        "The full execution trace shows exactly where things go wrong.",
        "TACTATACACAAACCACT",
        "TACCAGAACACATATCACT",
        { SOL_DEL(6), SOL_REV(3, 13) },
        2,
    },
    {
        13,
        "Same Protein, Different DNA",
        "Teach codon degeneracy",
        "The genetic code is redundant - multiple codons per amino acid",
        5, 6,
        12, 18,
        1, 1, 0, 0,
        13,
        2,
        CORRUPTION_RANDOM,
        "Different DNA sequences can produce the same amino acid.",
        "The genetic code has 64 codons but only 20 amino acids.",
        "Look at which codons are compatible with each target amino acid.",
        "The BFS validator ensures the shortest solution has the intended depth.",
        "TACCGCTTTGGGACT",
        "TACGGCTTTGGGACT",
        { SOL_DEL(4), SOL_INS(3, 'C') },
        2,
    },
    {
        14,
        "Full Repair",
        "Three-step planning (depth 3)",
        "Operation order changes positions, which changes reading frames",
        6, 7,
        18, 21,
        1, 1, 1, 0,
        14,
        3,
        CORRUPTION_DEL_INS_REV,
        "Each operation changes the tape, affecting what the next operation does.",
        "A deletion before your target position shifts that position left.",
        "An insertion before your target position shifts it right.",
        "Plan the full sequence of operations before executing.",
        "TACAAACGGTATGGCCAAATT",
        "TGAAAACCGGTTGGCAAACTT",
        { SOL_DEL(2), SOL_INS(11, 'A'), SOL_REV(3, 17) },
        3,
    },
    {
        15,
        "Codon Circuit",
        "All four operations, depth 4",
        "The complete Codon Circuit - reason about the full transformation",
        7, 7,
        12, 21,
        1, 1, 1, 1,
        15,
        4,      // MUST be depth 4 - all four tools required
        CORRUPTION_RANDOM,
        "All instruction types are available but quantities are limited.",
        "Think about the complete transformation needed.",
        "Consider which operations interact and in what order.",
        "The target defines exactly what the machine must produce.",
        "TACCGGACAACCATGGGAATC",
        "TACCGCACTAAGGTACAGAAC",
        { SOL_SWP(6, 18), SOL_DEL(17), SOL_REV(8, 13), SOL_INS(15, 'G') },
        4,
    }
};

#define NUM_LEVELS (sizeof(LEVELS) / sizeof(LEVELS[0]))

const LevelDefinition *level_get(int level_id)
{
    if (level_id < 1 || level_id > (int)NUM_LEVELS)
        return NULL;
    return &LEVELS[level_id - 1];
}

int level_count(void)
{
    return (int)NUM_LEVELS;
}

void level_print(const LevelDefinition *level)
{
    if (level == NULL) return;
    printf("Level %d: %s\n", level->level_id, level->objective);
    printf("  Target: %d-%d codons, Tape: %d-%d bases\n",
           level->target_codon_count_min, level->target_codon_count_max,
           level->tape_length_min, level->tape_length_max);
    printf("  Inventory: DEL=%d INS=%d REV=%d SWP=%d\n",
           level->delete_budget, level->insert_budget,
           level->reverse_budget, level->swap_budget);
    printf("  Difficulty: %d, Intended Depth: %d\n",
           level->difficulty, level->intended_depth);
    if (level->target_dna)
        printf("  Target DNA:   %s\n", level->target_dna);
    if (level->initial_dna)
        printf("  Initial DNA:  %s\n", level->initial_dna);
    printf("  Solution:     %d step(s)\n", level->solution_count);
}